import type { Metadata } from "next";

export const links = {
  ownerName: "Nazish Usaid",
  ownerEmail: "realnazishahmed@gmail.com",
} as const;

export const siteConfig: Metadata = {
  title: `Nazish Usaid`,
  description: "We are a passionate and driven team of software developers currently honing our skills at DCET. With expertise in product development, we specialize in building scalable, user-centric web applications and mobile applications that deliver seamless performance. We are currently building Electroplix, an IT services company focused on delivering cutting-edge technological solutions. From software development to cloud infrastructure and automation, Electroplix aims to provide businesses with scalable and efficient digital services.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "aceternity",
    "aceternity-ui",
    "shadcn",
    "shadcn-ui",
    "radix-ui",
    "cn",
    "clsx",
    "modern-portfolio",
    "portfolio",
    "3d-portfolio",
    "animated-portfolio",
    "nextjs-portfolio",
    "react-portfolio",
    "react-three-fiber",
    "three.js",
    "animated-website",
    "framer",
    "framer-motion",
    "three",
    "react-icons",
    "lucide-react",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: links.ownerName,
    url: "https://github.com/nazish-16",
  },
} as const;
